# -*- coding: utf-8 -*-
"""train.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v7jxUOEOCSPE2kuwFskm7BhRDcOkpaS8
"""

with open("train.py", "w") as f:
    f.write("""
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler
import joblib

# Load dataset
df = pd.read_csv("Mall_Customers.csv")

# Rename columns
df.columns = ['CustomerID','Gender','Age','AnnualIncome','SpendingScore']

# Select features
X = df[['AnnualIncome','SpendingScore']]

# Scale
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Train KMeans
kmeans = KMeans(n_clusters=5, random_state=42)
df['Cluster'] = kmeans.fit_predict(X_scaled)

# Save model and scaler
joblib.dump(kmeans, "kmeans_model.pkl")
joblib.dump(scaler, "scaler.pkl")

# Save clustered data
df.to_csv("clustered_customers.csv", index=False)

print("Model trained and files saved successfully")
""")